name: carder
favicon: null
layout_spectrum: 0.8131383408326656
typography_spectrum: 0.8944614394567907
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.24655852862633765
  lightness: 0.5698711250443012
  saturation: 0.8238502072636038
  rhythmicContrast: 0.942940650973469
purpose: []
