name: carder
favicon: null
layout_spectrum: 0.8131383408326656
typography_spectrum: 0.8944614394567907
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262624'
    - '#68a0d9'
    - '#9f0f04'
    - '#f5cfa0'
    - '#ff6a28'
  brandStrength: 0.1875
  lightness: 0.5698711250443012
  saturation: 0.8238502072636038
  rhythmicContrast: 0.942940650973469
purpose: []
